<table>
<tr>
<td width=15%><img src="https://www.nitrkl.ac.in/assets/images/logo.png"></img></td>
<td><center><h1>National Institute of Technology
Rourkela, Odisha, India, 769008</h1><h2>Department of Computer Science Engineering</h2></center></td>
</tr>
<tr><td colspan=2><center><h3>SUMMER INTERNSHIP cum TRAINNING PROGRAMME</h3></br>
            <b>(STTP: Introduction to Data Science using Python)</b></center></td></tr>
</table>

_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [1]:
import numpy as np

In [3]:
#Code here
arr = np.array([10, 5, 7, 20, 15, -9, 33])
max_value = np.max(arr)
min_value = np.min(arr)

print("Max value: ", max_value)
print("Min value: ", min_value)


Max value:  33
Min value:  -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [5]:
#Code here
def find_max(arr):
    max_value = arr[0]

    for element in arr[1:]:
        if element > max_value:
            max_value = element
    return max_value

arr = np.array(input("Enter the elements of the array: ").split(), dtype = int)
print("Maximum Value is: ", find_max(arr))


Maximum Value is:  70


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [8]:
#Code here
matrix1 = np.array([[1,2], [3,4]])
matrix2 = np.array([[2,4], [6,8]])

sum = matrix1 + matrix2
print("Sum of the matrix is: ", sum)

subtraction = matrix1 - matrix2
print("Subtraction of matrix is: ", subtraction)

Sum of the matrix is:  [[ 3  6]
 [ 9 12]]
Subtraction of matrix is:  [[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [14]:
#Code here
random_matrix = np.random.rand(5, 6)
print("Random matrix is: \n", random_matrix)

another_row = np.random.rand(1, 6)
random_matrix = np.vstack([random_matrix, another_row])
print("\nRandom matrix with another row is: \n", random_matrix)

sum = np.sum(random_matrix, axis = 1)
print("\nSum of each row is: ", sum)

Random matrix is: 
 [[0.9832255  0.56247992 0.96052608 0.26643216 0.22071635 0.16035822]
 [0.40904376 0.12882534 0.02269591 0.77199097 0.98642153 0.21153875]
 [0.17834926 0.7927361  0.55689021 0.91339738 0.45979276 0.39297237]
 [0.21529418 0.61659972 0.29629913 0.82187606 0.42219407 0.62966214]
 [0.36888256 0.60765637 0.15726181 0.92343056 0.04804212 0.87991788]]

Random matrix with another row is: 
 [[0.9832255  0.56247992 0.96052608 0.26643216 0.22071635 0.16035822]
 [0.40904376 0.12882534 0.02269591 0.77199097 0.98642153 0.21153875]
 [0.17834926 0.7927361  0.55689021 0.91339738 0.45979276 0.39297237]
 [0.21529418 0.61659972 0.29629913 0.82187606 0.42219407 0.62966214]
 [0.36888256 0.60765637 0.15726181 0.92343056 0.04804212 0.87991788]
 [0.45197796 0.23102484 0.71625357 0.78912031 0.45634728 0.20262892]]

Sum of each row is:  [3.15373823 2.53051627 3.29413807 3.0019253  2.9851913  2.84735288]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [15]:
#Code here
random_matrix = np.random.randint(0, 10, size = (5,6))
print("Random matrix is: \n", random_matrix)

another_column = np.random.randint(0, 10, size = (5,1))
random_matrix = np.hstack([random_matrix, another_column])
print("\nAnother column is: \n", another_column)

sine_matrix = np.sin(random_matrix)
print("Sine of the matrix is: \n", sine_matrix)

Random matrix is: 
 [[1 1 8 6 3 7]
 [0 0 8 4 2 9]
 [6 4 7 1 1 2]
 [2 0 8 3 4 2]
 [0 1 0 2 7 7]]

Another column is: 
 [[4]
 [2]
 [7]
 [7]
 [3]]
Sine of the matrix is: 
 [[ 0.84147098  0.84147098  0.98935825 -0.2794155   0.14112001  0.6569866
  -0.7568025 ]
 [ 0.          0.          0.98935825 -0.7568025   0.90929743  0.41211849
   0.90929743]
 [-0.2794155  -0.7568025   0.6569866   0.84147098  0.84147098  0.90929743
   0.6569866 ]
 [ 0.90929743  0.          0.98935825  0.14112001 -0.7568025   0.90929743
   0.6569866 ]
 [ 0.          0.84147098  0.          0.90929743  0.6569866   0.6569866
   0.14112001]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [16]:
#Code here
random_matrix = np.random.randint(0, 10, size = (5,6))
print("Random matrix is: \n", random_matrix)

result_matrix = random_matrix[2:4, 1:4]
print("\nResult matrix is: \n", result_matrix)

Random matrix is: 
 [[3 1 8 9 6 9]
 [8 2 6 3 4 8]
 [2 5 1 4 2 7]
 [7 7 7 0 0 7]
 [3 9 8 1 5 2]]

Result matrix is: 
 [[5 1 4]
 [7 7 0]]


### Great Job!